# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-27 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wally_trips', '0002_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='colors',
            name='incidents',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
