# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-27 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wally_trips', '0003_colors_incidents'),
    ]

    operations = [
        migrations.AddField(
            model_name='colors',
            name='city',
            field=models.CharField(default='Chicago', max_length=50),
            preserve_default=False,
        ),
    ]
