# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-27 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wally_trips', '0004_colors_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='colors',
            name='border',
            field=models.CharField(default=' x', max_length=25),
            preserve_default=False,
        ),
    ]
